name: Generate GitHub metrics
on:
  schedule:
    - cron:  "0 18 * * *"   # 매일 03:00 KST
  workflow_dispatch:

permissions:           # ← ❶ 추가
  contents: write      #   metrics.svg 커밋 허용

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user:  ${{ github.repository_owner }}
          template: classic
          base:   header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_habits:    yes
          plugin_habits_charts: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C