name: Metrics
on:
  schedule:
    - cron: '0 18 * * *'          # 매일 03:00 JST
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write                 # SVG 커밋 허용

jobs:
  metrics:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'  # 무한 커밋 루프 방지
    steps:
      - name: metrics2
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user:  SeungyeonHwang
          filename: metrics2.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          commits_authoring: syhwang.web@gmail.com, SeungyeonHwang
          # --- 핵심 플러그인 ---
          plugin_languages: yes
          plugin_languages_sections: recently-used, most-used
          plugin_languages_indepth: yes
          plugin_habits: yes
          plugin_isocalendar: yes
          plugin_activity: yes
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_repositories: yes
          plugin_topics: yes
          optimize: css               # SVG 용량 최적화  [oai_citation:10‡GitHub](https://github.com/lowlighter/metrics/discussions/1570?utm_source=chatgpt.com)
      - name: achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user:  SeungyeonHwang
          filename: achievements3.svg
          base: ""
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B